#ifndef BARE_METAL_DRIVER_LIBRARY_INC_STM32F407_GPIO_H_
#define BARE_METAL_DRIVER_LIBRARY_INC_STM32F407_GPIO_H_

#include "stm32f4xx.h"

/*
 *  GPIO Modes
 */
#define GPIO_MODE_IN		(0U)
#define GPIO_MODE_OUT		(1U)
#define GPIO_MODE_AF		(2U)
#define GPIO_MODE_AN		(3U)






#endif /* BARE_METAL_DRIVER_LIBRARY_INC_STM32F407_GPIO_H_ */
